##############################################
################ Peak Calling ################
##############################################

get_peak_calling_text <- function(peak_caller, consensus_method, pipeline = NULL) {
  
  if (peak_caller == "macs2") {
    # nf-core/atacseq workflow
    text <- paste0(
      "Raw ATAC-seq data were processed using the nf-core/atacseq 2.1.2 [^2] ",
      "([https://nf-co.re/atacseq/2.1.2/](https://nf-co.re/atacseq/2.1.2/)) pipeline. ",
      "Peak calling was performed with MACS2 in broad peak mode for each individual sample. ",
      "A consensus peakset was generated across all samples by merging all individual peak sets ",
      "using bedtools merge, without filtering for reproducibility or requiring presence in a ",
      "minimum number of replicates. This approach produces a union of all detected peaks ",
      "across all samples. Read counts were quantified over the global consensus peakset."
    )
    
  } else if (peak_caller == "genrich") {
    # Custom Genrich workflow  
    text <- paste0(
      "Raw ATAC-seq data were processed using a custom workflow. Peak calling was performed ",
      "with Genrich for each individual sample. A consensus peakset was generated by combining ",
      "all individual peak sets using GenomicRanges::reduce() to merge overlapping regions, ",
      "then filtering to retain only peaks present in at least 2 samples, ensuring robust ",
      "detection of reproducible accessible regions. This reproducibility-based filtering ",
      "approach reduces noise from singleton peaks while maintaining biologically relevant ",
      "accessible regions. Read counts were quantified over the consensus peakset using ",
      "featureCounts."
    )
    
  } else {
    stop("Unsupported peak_caller/consensus_method combination: ", peak_caller, "/", consensus_method)
  }
  
  return(text)
}

##############################################
################ Normalization ###############
##############################################

get_normalization_text <- function(has_spike_in, organism) {
  if (has_spike_in) {
    species <- if (organism == "mmu") "mouse" else "human"
    text <- paste0(
      "Spike-in normalization factors were calculated as the ratio of spike-in counts to ",
      species,
      " counts per sample, scaled by the median of these ratios. The inverse of these normalized ratios was assigned as the size factor for each sample in the ",
      species,
      " dataset, enabling normalization of counts based on spike-in abundance."
    )
  } else {
    text <- "Spike-in normalization was not available for this dataset. Counts were normalized using the TMM (Trimmed Mean of M-values) method to account for library size differences."
  }
  
  return(text)
}

##############################################
################ Annotation ##################
##############################################
# Detect annotation source based on column structure
detect_annotation_source <- function(peaks_anno) {
  col_names <- colnames(peaks_anno)
  
  # ChIPseeker format: seqnames, start, end, distanceToTSS, geneId
  if ("seqnames" %in% col_names && "start" %in% col_names && "distanceToTSS" %in% col_names) {
    return("chipseeker")
  }
  
  # HOMER format: Chr, Start, End, Distance.to.TSS  
  if ("Chr" %in% col_names && "Start" %in% col_names && "Distance.to.TSS" %in% col_names) {
    return("homer")
  }
  
  # Fallback detection - if we see HOMER-style caps but not the exact columns
  if (any(grepl("^[A-Z]", col_names)) && "Annotation" %in% col_names) {
    return("homer")
  }
  
  # Default fallback
  warning("Could not detect annotation source from column names. Assuming ChIPseeker.")
  return("chipseeker")
}

get_annotation_description_text <- function(peaks_anno) {
  annotation_source <- detect_annotation_source(peaks_anno)
  
  if (annotation_source == "homer") {
    text <- paste0(
      "Results of Differential Accessibility Analysis are provided below. ",
      "Peak annotation was performed using HOMER as implemented in the nf-core/atacseq pipeline. ",
      "Promoter regions were defined as peaks –1,000 bp to +100 bp relative to the transcription start site (TSS), ",
      "and this designation may differ from the HOMER derived annotation in the annotation column(s) ",
      "which uses the same promoter definition."
    )
  } else if (annotation_source == "chipseeker") {
    text <- paste0(
      "Results of Differential Accessibility Analysis are provided below. ",
      "Peak annotation was performed using ChIPseeker. ",
      "Promoter regions were defined as peaks ±1,000 bp from the transcription start site (TSS). ",
      "This promoter definition is consistent with the annotation categories shown in the results."
    )
  } else {
    # Fallback text
    text <- paste0(
      "Results of Differential Accessibility Analysis are provided below. ",
      "Peak annotation was performed and promoter regions were defined relative to transcription start sites (TSS)."
    )
  }
  
  return(text)
}
